services:
  api:
    build:
      context: ./shinydex-api
      args:
        UID: ${UID}
        GID: ${GID}
    container_name: shinydex-api
    volumes:
      - ./shinydex-api:/var/www/html
    environment:
      APP_ENV: dev
      APP_DEBUG: "1"
      DATABASE_URL: "mysql://shinydex:shinydex@db:3306/shinydex?serverVersion=8.0"
    depends_on:
      - db
    networks:
      - shinydex

  nginx:
    image: nginx:alpine
    container_name: shinydex-nginx
    ports:
      - "8000:80"
    volumes:
      - ./shinydex-api:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - shinydex

  app:
    build:
      context: ./shinydex-app
    container_name: shinydex-app
    volumes:
      - ./shinydex-app:/app
    ports:
      - "5173:5173"
    networks:
      - shinydex

  # app:
  #   image: node:20-alpine
  #   container_name: shinydex-app
  #   working_dir: /app
  #   volumes:
  #     - ./shinydex-app:/app
  #   ports:
  #     - "5173:5173"
  #   command: >
  #     sh -c "
  #     if [ ! -f package.json ]; then
  #       npm create vite@latest . -- --template react-ts &&
  #       npm install
  #     fi &&
  #     npm run dev -- --host
  #     "

  db:
    image: mysql:8.0
    container_name: shinydex-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shinydex
      MYSQL_USER: shinydex
      MYSQL_PASSWORD: shinydex
    volumes:
      - db_data:/var/lib/mysql   # <- volume Docker dédié
      - ./database/dumps:/dumps
    ports:
      - "3306:3306"
    networks:
      - shinydex

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: shinydex-phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: shinydex
      PMA_PASSWORD: shinydex
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - shinydex

networks:
  shinydex:
    driver: bridge

volumes:
  node_modules_app:
  db_data:
