api_platform:
    title: "ShinyDex API"
    version: "1.0.0"

    formats:
        jsonld: ["application/ld+json"]
        json:
            mime_types: ["application/json"]

    defaults:
        stateless: true
        normalization_context:
            enable_max_depth: true
        pagination_enabled: true
        pagination_items_per_page: 30
        pagination_client_items_per_page: false

    mapping:
        paths:
            - "%kernel.project_dir%/src/Entity"
            - "%kernel.project_dir%/src/Dto"
